### ISSUE TITLE
getValue missing?

### ISSUE THREAD

**Issue by Hauglid** [stefalda/localized-strings#16]
I can't seem to find getValue in the source code and I get an error when I try to use it. 

Property 'getValue' does not exist on type 'LocalizedStrings<....>'.

**Comment by chriscohoat** [comment]
Looking at the source code it's been renamed to `getString`. You can use it like this:
```
strings.getString('foo.bar', null, true)
```
The method takes parameters in the following format:
```
getString(key, language, omitWarning = false)
```
Here's a direct link: https://github.com/stefalda/localized-strings/blob/master/src/LocalizedStrings.js#L256

**Comment by Hauglid** [comment]
Thank you, this worked great!
